### PR TITLE
Restructure the Property Reference table

### PR DESCRIPTION
**Pull request by fifthposition**
I did remove some info from the 'Description' (now 'Information') text of one or two rows, because the table was fairly unwieldy. I attempted to preserve everything possible but simplify.

We do need to restructure the table in some way, because as is, it flows beyond the content area and the right-hand nav obscures part of the table as you scroll.

### CODE REVIEW

**Comment by fifthposition** [comment]
res-table

Here's how it looks with these changes.

**Comment by ssapra** [comment]
I wonder if it reads better if the type, required, and default were broken up into separate lines. And perhaps bold the prefix.

Example: 

**Type**: string 
**Required**: yes
**Default**: n/a

**Comment by fifthposition** [comment]
That does sound like it would be clearer. Here's how it looks:

res-table-formatting-improve

**Comment by ssapra** [comment]
Looks good to me!

**Pull request merged**
