### PR TITLE
Add new known issue for 1.1.0 release

### PR DESCRIPTION
**Pull request by ssapra**
Authored-by: Shaan Sapra <shsapra@vmware.com>

Name the branches to merge this change with or enter "None".

Feel free to edit the language as needed

### CODE REVIEW

**Comment by lenapivotal** [comment]
@ssapra I'm not sure what this means: "The Operator incorrectly assumes the table `performance_schema.keyring_component_status` exists when granting permissions to the `mysql-backup` user." 
How does the above stop 1.0.0 from restarting or starting fresh?

**Comment by ssapra** [comment]
In a 1.0.0 instance, the table `performance_schema.keyring_component_status` doesn't exist. It's a new system table that is added in Percona MySQL 8.0.25. 

So the operator code was updated to grant permissions to the `mysql-backup` user for that table, but we didn't consider the situation where a 1.0.0 instance is created (using Percona MySQL 8.0.22) where the table doesn't exist (and so the permission grant fails and blocks the creation of the 1.0.0 instance).

Hope that helps!

**Comment by lenapivotal** [comment]
> In a 1.0.0 instance, the table `performance_schema.keyring_component_status` doesn't exist. It's a new system table that is added in in 1 1.0 instance (that uses Percona MySQL 8.0.25)
> 
> So the operator code was updated to grant permissions to the `mysql-backup` user for that table, but we didn't consider the situation where a 1.0.0 instance is created (using Percona MySQL 8.0.22) where the table doesn't exist (and so the permission grant fails and blocks the creation of the 1.0.0 instance).
> 
> Hope that helps!

Thank you,  definitely helps.

**Comment by lenapivotal** [comment]
Will close this PR and will not merge as is. I have merged it with master, rephrased, and then cherry-picked to 1.1. 
It is live on 1.1 and also exists on master too 
https://docs-mysql-k8s-wip.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-1/release-notes.html. Should have done it the other way around but hey, same result.

**Pull request closed without merging**
