### PR TITLE
Create TLS secret with CA included

### PR DESCRIPTION
**Pull request by ssapra**
[#177033298](https://www.pivotaltracker.com/story/show/177033298)

Co-authored-by: Colin Shield <cshield@vmware.com>
Co-authored-by: Shaan Sapra <shsapra@vmware.com>

Name the branches to merge this change with or enter "None".

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @ssapra and @colins 
Will merge and check for style/formatting and get back to you with any questions.

**Comment by jncd** [comment]
Hello again @ssapra and @colins 

I tidied the formatting. I have a question about the use of both `TLS-SECRET-NAME` and `SECRET-NAME` — I was confused. 
Would it work to change  `TLS-SECRET-NAME` to `TLS-SECRET` ?

Screen Shot 2021-03-08 at 5 40 39 PM

**Comment by ssapra** [comment]
Ah, yes, we should use the same placeholder variable name. There are other examples where we use `INSTANCE-NAME` or `BACKUP-NAME`, so I'm wondering if we should consolidate on `TLS-SECRET-NAME`.

**Comment by jncd** [comment]
So, on that page, `TLS-SECRET-NAME` and `SECRET-NAME` are identical? 
Even though they are described differently? 
 
"`SECRET-NAME` is the name you choose for the TLS Secret."
"`TLS-SECRET-NAME` is the value of the `spec.secretName` from the Certificate, recorded in step 5 above."

If so, let's go with `TLS-SECRET-NAME`.

**Comment by ssapra** [comment]
Yes they are identical, so we can stick with `TLS-SECRET-NAME`. We can actually remove Step 6 because Step 4 is doing the same action.

**Comment by jncd** [comment]
Thanks! Very good! I standardized on `TLS-SECRET-NAME` and removed step 6. 

Additional questions:

Q1. I'm wondering now about step 5. What is the relation between the `TLS-SECRET-NAME` and the `spec.secretName` ?  
Q2. The doc says to record this name but does not say why. This term `spec.secretName` is not mentioned elsewhere in the doc.
Q3. There was a cross-reference to troubleshooting certificate creation:  "see the [cert-manager documentation](https://cert-manager.io/docs/faq/troubleshooting/)". At the end of (removed) step 6. Should we keep it? Is there a particular step where the customer is likely to have trouble? 

Screen Shot 2021-03-09 at 4 49 10 PM

Or, view [on staging.](https://docs-pcf-staging.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-n/configure-tls.html#using-cert-manager)

**Pull request merged**
