### PR TITLE
Add manual instructions to connect a TAS app to this mysql K8s instance

### PR DESCRIPTION
**Pull request by dsboulder**
@colins and I tried this and it eventually worked.

Thanks folks!

### CODE REVIEW

**Comment by dsboulder** [comment]
@colins do you recommend tagging anyone in particular here? Does @lenapivotal also do docs for MySQL on K8s?

**Comment by lenapivotal** [comment]
> @colins do you recommend tagging anyone in particular here? Does @lenapivotal also do docs for MySQL on K8s?

@dsboulder I've just taken ownership of these docs also :) So I'll add to our docs tracker

**Comment by dsboulder** [comment]
Thanks @lenapivotal, would love you help publishing these soon since I have a customer meeting tomorrow

**Comment by lenapivotal** [comment]
> Thanks @lenapivotal, would love you help publishing these soon since I have a customer meeting tomorrow

@dsboulder we cannot respond as quickly to these PRs as you hoped. Priority is the postgres for k8s 1.2 and we'll start looking at mysql after. If there is an urgent need to show integration steps to the customer, I'm sure they will be ok with a google doc and we can let them know that the next product release will have the official docs. 
I appreciate your patience, I promise you we're doing the best we can.

**Pull request merged**
