### PR TITLE
Feature/update overview 175978215

### PR DESCRIPTION
**Pull request by abg**
We have filled out the index page with some additional "overview" information, including a high-level architecture diagram.

We added some docs around the custom resources the Tanzu MySQL operator supports with some example input and expected output.

We left the backup concerns alone for now (RTO / RPO, etc.) because we think we will deal with these in a future PR.

Most of these additions are pretty rough and could use some polishing with helps from the docs team.

### CODE REVIEW

**Comment by jncd** [comment]
Thanks very much @abg 
I've merged and will take a look.

**Comment by jncd** [comment]
'Looking good so far. I'm about halfway through the topic. First question: 
Screen Shot 2020-12-07 at 4 07 41 PM

**Comment by dsharp-pivotal** [comment]
These are the official MySQL 8.0 release notes:
- https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html
- https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html

That's quite overwhelming, though.

Also, this list was not written as a list of "new features", as most of that was in historical versions of MySQL. Rather, it's an analogue of the feature list for the Postgres product:
https://postgres.docs.pivotal.io/11-1/about.html

**Comment by jncd** [comment]
Hi David,
Thanks for all this clarification. I didn't pick up on the fact that the feature list wasn't new-in-MySQL 8.0 but rather a general list of features in MySQL. I'll try to restructure this to make more sense.
Jane

**Comment by jncd** [comment]
Here's another one that's too subtle for me. Some things are separated by semicolons, some with parentheses and others with hyphens... why the variation? and why is bucketPath not described? 



Could this just be reformatted as a table? 

| Field | Description | Required |
|------|-------------|----------|
|  `bucket` | Name of the storage bucket for this backup location | Yes |

**Comment by dsharp-pivotal** [comment]
I don't think there's any secret meaning behind the punctuation, just run-of-the-mill inconsistency. Formatting as a table makes sense to me. We were told to minimize markdown, so that may be part of it. Perhaps a column for defaults would be good as well?

Here's a description for bucketPath:

> - bucketPath: Path prefix within the bucket to store backups. default: no prefix.

- For forcePathStyle: The default should probably say `false` somewhere, as well as the meaning.
- For disableSSL: The default here is `false` as well.

**Pull request merged**
