### PR TITLE
Clarify tls sans 177564166

### PR DESCRIPTION
**Pull request by kimago**
Substantial TLS clarifications

    - Pulled SAN topic into standalone bullet point for further
      consideration / clarification
    - Clarified ClusterIssuer vs Issuer usage WRT namespace
    - Delineated `spec.dnsNames`/`spec.ipAddresses` into distinct cases
      "within same cluster" vs "outside cluster"
    - Replaced example of port forwarded client connection with client
      connecting to load-balanced service (presumably closer to a real-
      world developer scenario).
    - (Small markdown adjusutments WRT numbering spacing etc.)

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @kimago, does this change apply to any branches other than main?

**Comment by colins** [comment]
Just the main branch. Thanks

**Comment by jncd** [comment]
Question 1: About this line:

> The server hostname will be the DNS name you use when connecting your app to the MySQL instance.

The page about connecting apps doesn't contain the terms "server hostname", "hostname", or "DNS name". 
However, in does have the spec:
```
spec:
  isCA: false
  dnsNames:
    - mysql-sample.default # SEE NOTE AT END
```

So, I'm writing instead: 
> "The server hostname is the DNS name that you use when connecting your app to the MySQL instance, for example, `mysql-sample.default`."

I'm thinking that will help readers make the _mental_ connection. (If that's correct.)

**Comment by jncd** [comment]
"specify" vs "supply"?
"request yaml" vs "request" vs _nowhere_
These steps look very wordy when rendered. If all these things are specified in the request YAML, we can simplify into a table for easier reading.


Screen Shot 2021-04-13 at 5 57 13 PM

**Comment by jncd** [comment]
"mysql CLI client" vs "mysql client" vs " local mysql client"?   Are these the same or different?
Just about everywhere else we use mixed case. Why is this lowercase? 

> "You _can_ save that certificate out to a local file ca.crt by running:"  
Says I can do it, but do I need to do it? (or should it be marked optional?)

**Comment by abg** [comment]
> "mysql CLI client" vs "mysql client" vs " local mysql client"? Are these the same or different?
> Just about everywhere else we use mixed case. Why is this lowercase?

These are definitely the same thing in this context.   "mysql" was probably listed in lowercase because the command run is `mysql` - "[The MySQL Command-Line Client](https://dev.mysql.com/doc/refman/8.0/en/mysql.html)".

> > "You _can_ save that certificate out to a local file ca.crt by running:"
> > Says I can do it, but do I need to do it? (or should it be marked optional?)

The ca.crt is needed for [the example](https://github.com/pivotal-cf/docs-mysql-k8s/blob/9a6c4483fc77cfd0efcd47eee794fb7630be48b1/configure-tls.html.md.erb#L250) in step (4) in this context, because the example uses the MySQL command-line client to connect to the instance, and verify the database server certificate with the certificate authority it was signed by  (ca.crt).

**Comment by jncd** [comment]
Hello @kimago and @abg I've attempted a big rationalization of this [page](https://docs-pcf-staging.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-n/configure-tls.html). Put specific questions in a [google doc](https://docs.google.com/document/d/1DG0ftJGv67F_itUULbXpuD4U7iPzsolKSLsm2ZfhUMk/edit?usp=sharing). See [docs story](https://www.pivotaltracker.com/story/show/177694238) for details. Let's meet up next week.

**Comment by jncd** [comment]
Hello @kimago and @abg 
An update on this PR. David Sharp worked through my questions in the google doc and spent time with me today. 
Here's the final result on staging. The [table in step 4](https://docs-pcf-staging.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-0/configure-tls.html#using-cert-manager) for cert-manager would probably most benefit from your review.

FYI: Attached is a snapshot of the original PR text.
before

**Pull request merged**
